[tool.black]
line-length = 100  
# target-version = ['py312'] # Опционально, если хочешь указать версии Python, под которые форматировать
# include = '\.pyi?$'
# exclude = '''
# /(
#     \.eggs
#   | \.git
#   | \.hg
#   | \.mypy_cache
#   | \.tox
#   | \.venv
#   | _build
#   | buck-out
#   | build
#   | dist
# )/
# '''