#########################################################################
# Параметры для Cycle-Consistent Generative Adversarial Networ (CycleGAN)
#########################################################################

# Путь к директории, где лежат .pth файлы моделей
MODELS_DIR: "app/models/cyclegan"

# Параметры устройства 
# Варианты: "auto"(автоматически использовать GPU если доступно), "cuda", "cpu"
DEVICE: "auto"

# --- Параметры архитектуры генератора (для стандартных моделей) ---
INPUT_CHANNELS: 3
OUTPUT_CHANNELS: 3
NUM_RESIDUAL_BLOCKS: 9
IMAGE_SIZE: 512


styles:
  monet:
    display_name: "🎨 Стиль Моне"
    model_file: "style_monet.pth"
  vangogh:
    display_name: "🌟 Стиль Ван Гога"
    model_file: "style_vangogh.pth"
  horse2zebra:
    display_name: "🐴➡️🦓 Лошадь в зебру"
    model_file: "horse2zebra.pth"  
