# Параметры для Neural Style Transfer (NST)

# Пути к ресурсам
MODEL_PATH: "models/vgg19-dcbb9e9d.pth"
TEMP_IMAGE_DIR: "temp_images"
DEFAULT_STYLE_IMAGE_DIR: "static/style_images"

# Параметры устройства 
# Варианты: "auto"(автоматически использовать GPU если доступно), "cuda", "cpu"
DEVICE: "auto"


# Размер изображения(в пикселях по ширине и высоте, предполагается квадратное изображение),
# который будет использоваться при обработке. Входные изображения будут масштабироваться 
# к указанному размеру автоматически.
IMAGE_SIZE: 128  # по-дефолту
IMAGE_SIZE_CPU: 256
IMAGE_SIZE_CUDA: 512

# Нормализация для VGG19 (ImageNet)
# Стандартные значения нормализации для VGG19, обученной на ImageNet. Изменение этих значений 
# (если только вы не используете другую предобученную модель с другими параметрами нормализации) 
# скорее всего ухудшит результат, так как признаки будут извлекаться некорректно.
NORMALIZATION_MEAN: [0.485, 0.456, 0.406]
NORMALIZATION_STD: [0.229, 0.224, 0.225]

# Слои для извлечения признаков
CONTENT_LAYERS:
  - "conv_4"
STYLE_LAYERS:
  - "conv_1"
  - "conv_2"
  - "conv_3"
  - "conv_4"
  - "conv_5"

# Параметры оптимизации
NUM_STEPS: 200 
STYLE_WEIGHT: 1000000
CONTENT_WEIGHT: 1